apiVersion: v1
kind: ConfigMap
metadata:
  name: product-order-system-config
data:
  USER_SERVICE_URL: "http://user-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  USER_SERVICE_PORT: "3001"
  PRODUCT_SERVICE_PORT: "3002"
  ORDER_SERVICE_PORT: "3003"
