apiVersion: v1
kind: Secret
metadata:
  name: product-order-system-secret
type: Opaque
data:
  # mongodb://mongodb-user:27017/userdb
  USER_MONGO_URI: bW9uZ29kYjovL21vbmdvZGItdXNlcjoyNzAxNy91c2VyZGI=
  # mongodb://mongodb-product:27017/productdb
  PRODUCT_MONGO_URI: bW9uZ29kYjovL21vbmdvZGItcHJvZHVjdDoyNzAxNy9wcm9kdWN0ZGI=
  # mongodb://mongodb-order:27017/orderdb
  ORDER_MONGO_URI: bW9uZ29kYjovL21vbmdvZGItb3JkZXI6MjcwMTcvb3JkZXJkYg==
